import { useState } from 'react'
import { FileText, TrendingUp, Shield, MessageCircle, AlertTriangle, Calculator, Download } from 'lucide-react'
import KeyMetrics from './KeyMetrics'
import ClauseBreakdown from './ClauseBreakdown'
import RiskChecklist from './RiskChecklist'
import QAChat from './QAChat'
import EMICalculator from './EMICalculator'

const TABS = [
  { id: 'overview', label: 'Overview', icon: TrendingUp },
  { id: 'clauses', label: 'Clauses', icon: FileText },
  { id: 'risks', label: 'Risk Report', icon: Shield },
  { id: 'calculator', label: 'EMI Calculator', icon: Calculator },
  { id: 'qa', label: 'Ask AI', icon: MessageCircle },
]

function RiskScoreGauge({ score }) {
  const angle = ((score - 1) / 9) * 180
  const color = score <= 3 ? '#10b981' : score <= 6 ? '#f59e0b' : '#ef4444'
  const label = score <= 3 ? 'Low Risk' : score <= 6 ? 'Moderate Risk' : 'High Risk'

  return (
    <div className="flex flex-col items-center">
      <div className="relative w-36 h-20">
        <svg viewBox="0 0 120 65" className="w-full">
          <path d="M 10 60 A 50 50 0 0 1 110 60" fill="none" stroke="#1e2d52" strokeWidth="8" strokeLinecap="round" />
          <path d="M 10 60 A 50 50 0 0 1 43 17" fill="none" stroke="#10b981" strokeWidth="8" strokeLinecap="round" opacity="0.3" />
          <path d="M 43 17 A 50 50 0 0 1 77 17" fill="none" stroke="#f59e0b" strokeWidth="8" strokeLinecap="round" opacity="0.3" />
          <path d="M 77 17 A 50 50 0 0 1 110 60" fill="none" stroke="#ef4444" strokeWidth="8" strokeLinecap="round" opacity="0.3" />
          <line
            x1="60" y1="60"
            x2={60 + 38 * Math.cos(((angle - 180) * Math.PI) / 180)}
            y2={60 + 38 * Math.sin(((angle - 180) * Math.PI) / 180)}
            stroke={color} strokeWidth="3" strokeLinecap="round"
          />
          <circle cx="60" cy="60" r="4" fill={color} />
        </svg>
      </div>
      <div className="text-center -mt-2">
        <span className="text-4xl font-display font-bold" style={{ color }}>{score}</span>
        <span className="text-slate-500 text-sm">/10</span>
        <div className="text-sm font-medium mt-0.5" style={{ color }}>{label}</div>
      </div>
    </div>
  )
}

function downloadReport(data) {
  const { analysis, filename, pages, word_count } = data
  const a = analysis
  const lines = [
    '═══════════════════════════════════════════════════════',
    '       FinDocGenAI — Financial Document Analysis',
    '        ET GenAI Hackathon 2026 | PS9 AI Money Mentor',
    '═══════════════════════════════════════════════════════',
    '',
    `Document : ${filename}`,
    `Type     : ${a.document_type}`,
    `Issuer   : ${a.issuer}`,
    `Pages    : ${pages}   |   Words: ${word_count?.toLocaleString()}`,
    `Risk Score: ${a.overall_risk_score}/10 — ${a.risk_summary}`,
    '',
    '─── SUMMARY ────────────────────────────────────────────',
    a.summary,
    '',
    '─── KEY FINANCIAL METRICS ───────────────────────────────',
  ]
  const m = a.key_metrics || {}
  Object.entries(m).forEach(([k, v]) => {
    if (v && v !== 'null') lines.push(`  ${k.replace(/_/g,' ').padEnd(22)}: ${v}`)
  })
  lines.push('')
  lines.push('─── AI ADVICE ───────────────────────────────────────────')
  lines.push(a.borrower_advice)
  lines.push('')
  if (a.red_flags?.length) {
    lines.push('─── RED FLAGS ───────────────────────────────────────────')
    a.red_flags.forEach(f => lines.push(`  ⚠ ${f}`))
    lines.push('')
  }
  if (a.clauses?.length) {
    lines.push('─── CLAUSE BREAKDOWN ────────────────────────────────────')
    a.clauses.forEach(c => {
      lines.push(`  [${c.importance?.toUpperCase()}] ${c.title} (${c.category})`)
      lines.push(`    ${c.plain_english}`)
      if (c.borrower_impact) lines.push(`    → ${c.borrower_impact}`)
      lines.push('')
    })
  }
  if (a.risk_items?.length) {
    lines.push('─── RISK ITEMS ──────────────────────────────────────────')
    a.risk_items.forEach(r => {
      lines.push(`  [${r.severity?.toUpperCase()}] ${r.title}`)
      lines.push(`    ${r.description}`)
      if (r.recommendation) lines.push(`    ✓ ${r.recommendation}`)
      lines.push('')
    })
  }
  if (a.hidden_charges?.length) {
    lines.push('─── HIDDEN CHARGES ──────────────────────────────────────')
    a.hidden_charges.forEach(c => lines.push(`  • ${c.name}: ${c.amount || '—'}  (${c.when_triggered || '—'})`))
    lines.push('')
  }
  lines.push('═══════════════════════════════════════════════════════')
  lines.push('Generated by FinDocGenAI | ET GenAI Hackathon 2026')
  lines.push('This is an AI analysis for informational purposes only.')
  lines.push('Consult a qualified financial advisor before signing.')
  lines.push('═══════════════════════════════════════════════════════')

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `FinDocGenAI_${filename.replace('.pdf','')}_Report.txt`
  link.click()
  URL.revokeObjectURL(url)
}

export default function Dashboard({ data, apiUrl }) {
  const [activeTab, setActiveTab] = useState('overview')
  const { analysis, filename, pages, word_count, session_id } = data
  const riskScore = analysis?.overall_risk_score || 5

  return (
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Document header bar */}
      <div className="card mb-6 fade-up">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-gold-500/10 border border-gold-500/20 rounded-xl flex items-center justify-center">
              <FileText className="w-6 h-6 text-gold-400" />
            </div>
            <div>
              <h2 className="font-semibold text-white truncate max-w-xs sm:max-w-md">{filename}</h2>
              <div className="flex items-center gap-4 mt-0.5">
                <span className="text-xs text-slate-500">{pages} pages</span>
                <span className="text-xs text-slate-500">{word_count?.toLocaleString()} words</span>
                <span className="text-xs text-gold-400 font-medium">{analysis?.document_type}</span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={() => downloadReport(data)}
              className="btn-ghost flex items-center gap-2 text-sm"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download Report</span>
            </button>
            <RiskScoreGauge score={riskScore} />
          </div>
        </div>

        {analysis?.summary && (
          <>
            <div className="glow-line my-4" />
            <p className="text-slate-300 text-sm leading-relaxed">{analysis.summary}</p>
          </>
        )}

        {analysis?.red_flags?.length > 0 && (
          <div className="mt-4 flex flex-wrap gap-2">
            {analysis.red_flags.slice(0, 4).map((flag, i) => (
              <div key={i} className="flex items-center gap-1.5 bg-red-500/10 border border-red-500/20 rounded-full px-3 py-1">
                <AlertTriangle className="w-3 h-3 text-red-400 flex-shrink-0" />
                <span className="text-xs text-red-300">{flag}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Tabs */}
      <div className="border-b border-[#1e2d52] mb-6 fade-up fade-up-2">
        <div className="flex gap-1 overflow-x-auto pb-px">
          {TABS.map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={`flex items-center gap-2 px-5 py-3 text-sm font-medium whitespace-nowrap transition-all duration-200 ${
                activeTab === id ? 'tab-active' : 'tab-inactive'
              }`}
            >
              <Icon className="w-4 h-4" />
              {label}
              {id === 'risks' && riskScore >= 7 && (
                <span className="w-2 h-2 bg-red-400 rounded-full" />
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Tab content */}
      <div className="fade-up fade-up-3">
        {activeTab === 'overview' && (
          <KeyMetrics metrics={analysis?.key_metrics} advice={analysis?.borrower_advice} issuer={analysis?.issuer} />
        )}
        {activeTab === 'clauses' && (
          <ClauseBreakdown clauses={analysis?.clauses || []} />
        )}
        {activeTab === 'risks' && (
          <RiskChecklist
            risks={analysis?.risk_items || []}
            hiddenCharges={analysis?.hidden_charges || []}
            riskScore={riskScore}
            riskSummary={analysis?.risk_summary}
          />
        )}
        {activeTab === 'calculator' && (
          <EMICalculator metrics={analysis?.key_metrics} />
        )}
        {activeTab === 'qa' && (
          <QAChat sessionId={session_id} apiUrl={apiUrl} />
        )}
      </div>
    </main>
  )
}
